name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: content

      - name: Checkout Quartz repo
        uses: actions/checkout@v4
        with:
          repository: jackyzha0/quartz
          path: quartz

      - name: Copy Settings
        run: |
          cp content/quartz.config.ts quartz/quartz.config.ts
          cp content/quartz.layout.ts quartz/quartz.layout.ts

      - name: Npm install
        working-directory: quartz
        run: |
          npm install

      - name: Create symbolic link
        working-directory: quartz
        run: |
          ln -s ../content content

      - name: Build
        working-directory: quartz
        run: |
          npx quartz build

      - name: Push updated files to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: quartz/content

